# Generated by Django 3.1.4 on 2020-12-16 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=20)),
                ('cuit', models.CharField(max_length=13)),
                ('cond_afif', models.CharField(max_length=8)),
                ('tipo', models.CharField(max_length=4)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=10)),
                ('codpost', models.CharField(max_length=8)),
                ('bonificacion', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('empleado', models.BooleanField()),
                ('esposa', models.BooleanField()),
                ('hijos', models.IntegerField()),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=10)),
                ('codpost', models.CharField(max_length=8)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='telefonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=8)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.personas')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(default='producto', max_length=150)),
                ('cantidad', models.BigIntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margen', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ubicacion', models.CharField(max_length=8)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='items_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.productos')),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.personas'),
        ),
    ]
